#!/usr/bin/env bash
APPZ_MNGR_VERSION="0.0.1"
APPZ_MNGR_NAME="yarn"

appz_clean(){
	yarn cache clean
}
appz_has(){
	echo "not supported"
}
appz_install() {
	yarn global add "$@"
}
appz_list(){
	yarn global list
}
appz_remove(){
	yarn global remove "$@"
}
appz_search(){
	echo "not supported"
}
appz_show(){
	yarn info "$@" description
}
appz_update(){
	yarn global upgrade-interactive
}
appz_upgrade(){
	yarn global upgrade
}
