#!/usr/bin/env bash
APPZ_MNGR_VERSION="0.0.1"
APPZ_MNGR_NAME="yay"

yay_packagelist="${APPZ_CACHE_DIR:?}/yay_packagelist"

appz_list(){
	local selected_app=$(yay -Qmq | fzf -i -e -m --preview 'pacman -Qil {}' --layout=reverse -q "${*:-}" )
	[ -z "$selected_app" ] && return 0
	pacman -Qi "$selected_app"
	_prompt "do you wanna uninstall $selected_app ?" && yay -Rs "$selected_app"
}

appz_search_get_yay_packagelist(){
	if ! is_file_uptodate "${yay_packagelist:?}"; then
		{ ping -q -c 1 example.org >/dev/null 2>&1 && yay -Salq > "${yay_packagelist:?}" ;}
	fi
	cat "${yay_packagelist:?}"
}

appz_search(){
	local selected_app=$(appz_search_get_yay_packagelist | fzf -i -e -m --preview 'yay -Si {}' --layout=reverse -q "${*:-}" )
	[ -z "$selected_app" ] && return 0
	yay -Si "$selected_app"
	_prompt "do you wanna install $selected_app ?" && yay -Sa "$selected_app"
}

appz_install() {
	if [ ! -n "$2" ]; then
		local selected_app=$(yay -Ssq | fzf -i -e --preview 'yay -Si {}' --layout=reverse -q "${*:-}" --select-1)
		[ -z "$selected_app" ] && return 0
		echo "installing $selected_app : "
		yay -Sa "$selected_app"
	else
		yay -Sa "$@"
	fi
}
appz_update(){
	yay -Qua
}

appz_upgrade(){
	yay -Sua
}

appz_show(){
	yay -Sia "$@"
}

appz_remove(){
	if [ ! -n "$2" ]; then
		local selected_app=$(yay -Qmq | fzf -i -e --preview 'pacman -Qil {}' --layout=reverse -q "${*:-}" --select-1)
		[ -z "$selected_app" ] && return 0
		echo "uninstalling $selected_app : "
		yay -Rs "$selected_app"
	else
		yay -Rs "$@"
	fi
}

appz_has(){
	while [ "$1" ]; do
		if $(yay -Qqma $1 >/dev/null 2>&1); then
			printf ' %s \033[32;1m\t%s \033[0m\n' "- $1" "installed"
		elif $(yay -Ssq "^$1" >/dev/null 2>&1); then
			printf ' %s \033[31;1m\t%s \033[0m\n' "- $1" "not installed"
		else
			printf ' %s \033[31;1m\t%s \033[0m\n' "- $1" "not available in pacman"
		fi
		shift
	done
}

appz_clean(){
	yay -Yc
	yay -Sca
}

appz_count(){
	yay -Qqm | tot
}
